#!/bin/sh
MSG=`awk '{printf("%s",$0)}' $1`
if [ ${#MSG} -lt 5 ]  
  then
    echo "-----------"
    echo "commit message 只有${#MSG}字符"
    echo "message的长度不能小于5, 本次提交失败，请完善commit message，再提交"
    echo "-----------"
    exit 1; #如果该钩子脚本以非零值退出，Git 将放弃提交
fi