# Generated by Django 3.2.13 on 2022-08-01 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F5Pools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=20)),
                ('server', models.CharField(max_length=100)),
                ('environment', models.SmallIntegerField(choices=[(1, 'DEV'), (2, 'INT'), (3, 'QA'), (4, 'QA3'), (5, 'QA4'), (6, 'PIE'), (7, 'PRF'), (8, 'HFP'), (9, 'HFQ'), (10, 'STG'), (99, 'PROD')], default='')),
            ],
        ),
        migrations.CreateModel(
            name='F5PoolMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poolname', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_f5.f5pools')),
            ],
        ),
    ]
